### ISSUE TITLE
Solidify Use Case for Interactive Event Storming

### ISSUE THREAD

**Issue by javaplus** [javaplus/StreamingWorkshop#1]
Come up with use case for interactive Event Storming session

**Comment by javaplus** [comment]
We will use a domain that most people should be familiar with in order to do the interactive Event storming.  Perhaps it's ordering a Pizza online or ordering something from Amazon.

Then we will have a completed Event Storming board for the College Book Exchange scenario that they will be coding.

**Comment by davidlday** [comment]
Miro board created to host the interactive portion using a trip to the grocery store as the exercise domain.

**Comment by davidlday** [comment]
Board created. College Cafe will be used as a finished example (at least for Textbook Exchange).
